'use strict';

const { PIXAI_PROFILE_ID } = require('./pluginModelRegistry.cjs');
const { SessionError } = require('./pluginModelSessions.cjs');
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MAX = 32 * 1024 * 1024;
const MAX_OPTIONS = 2048;
const error = (code, message, retryable = false) => new SessionError(code, message, retryable);
function status(code) { return ({ NOT_FOUND: 404, UNSUPPORTED: 400, INVALID_ARGUMENT: 400, RESOURCE_LIMIT: 429, CONFLICT: 409, ABORTED: 499, DECODE_FAILED: 400, PROVIDER_ERROR: 502 })[code] ?? 500; }
function respond(res, value, code = 200) { res.setHeader?.('Cache-Control', 'no-store'); res.status?.(code).json(value); }
function safe(res, value) { const e = value instanceof SessionError ? value : error('PROVIDER_ERROR', 'Inference provider failed', true); respond(res, { error: { code: e.code, message: e.message, retryable: Boolean(e.retryable) } }, status(e.code)); }
function header(req, name) { const value = req.headers?.[name]; return typeof value === 'string' ? value : undefined; }
function owner(req) { const principalId = header(req, 'x-risu-plugin-principal-id'), instanceId = header(req, 'x-risu-plugin-instance-id'); if (!UUID.test(principalId ?? '') || !UUID.test(instanceId ?? '')) throw error('INVALID_ARGUMENT', 'Invalid plugin identity'); return { principalId, instanceId }; }
function empty(req) { const length = header(req, 'content-length'), transfer = header(req, 'transfer-encoding'); if (transfer !== undefined || (length !== undefined && length !== '0')) throw error('INVALID_ARGUMENT', 'Request body is forbidden'); }
function options(text) { if (text === undefined) return undefined; if (Buffer.byteLength(text, 'utf8') > MAX_OPTIONS) throw error('INVALID_ARGUMENT', 'Invalid inference options'); const seen = new Set(), matcher = /"((?:\\.|[^"\\])*)"\s*:/g; let match; while ((match = matcher.exec(text))) { if (seen.has(match[1])) throw error('INVALID_ARGUMENT', 'Invalid inference options'); seen.add(match[1]); } let value; try { value = JSON.parse(text); } catch { throw error('INVALID_ARGUMENT', 'Invalid inference options'); } if (!value || typeof value !== 'object' || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) throw error('INVALID_ARGUMENT', 'Invalid inference options'); const keys = Object.keys(value); if (keys.some((key) => !['thresholds', 'categories', 'maxResults'].includes(key))) throw error('INVALID_ARGUMENT', 'Invalid inference options'); return value; }
async function body(req, length) { if (!/^[1-9]\d*$/.test(length) || Number(length) > MAX) throw error('INVALID_ARGUMENT', 'Invalid image length'); let total = 0; const values = []; if (req.readableAborted || req.destroyed) throw error('ABORTED', 'Inference aborted'); for await (const value of req) { if (!Buffer.isBuffer(value)) throw error('INVALID_ARGUMENT', 'Invalid image body'); total += value.length; if (total > Number(length)) throw error('INVALID_ARGUMENT', 'Invalid image length'); values.push(value); } if (total !== Number(length)) throw error('INVALID_ARGUMENT', 'Invalid image length'); return Buffer.concat(values, total); }
function profile(req) { if (req.params?.profileId !== PIXAI_PROFILE_ID) throw error('NOT_FOUND', 'Model profile not found'); return PIXAI_PROFILE_ID; }

function registerPluginModelInferenceRoutes({ app, broker, checkAuth, checkActiveSession }) {
    async function auth(req, res, active) { if (!await checkAuth(req, res)) return false; if (active && !checkActiveSession(req, res)) return false; return true; }
    app.get('/api/plugin-model-inference/:profileId/capabilities', async (req, res) => { if (!await auth(req, res, false)) return; try { respond(res, await broker.probe(profile(req))); } catch (e) { safe(res, e); } });
    app.post('/api/plugin-model-inference/:profileId/sessions', async (req, res) => { if (!await auth(req, res, true)) return; try { const ids = owner(req); empty(req); const provider = header(req, 'x-risu-local-model-provider') ?? 'auto'; if (!['auto', 'node'].includes(provider)) throw error(provider === 'webgpu' || provider === 'wasm' ? 'UNSUPPORTED' : 'INVALID_ARGUMENT', 'Unsupported inference provider'); const controller = new AbortController(); let responded = false; req.once?.('aborted', () => controller.abort()); res.once?.('close', () => { if (!responded) controller.abort(); }); const value = await broker.acquire({ ...ids, profileId: profile(req), provider, signal: controller.signal }); responded = true; respond(res, value); } catch (e) { safe(res, e); } });
    app.post('/api/plugin-model-inference/:profileId/sessions/:sessionId/run', async (req, res) => { if (!await auth(req, res, true)) return; try { const ids = owner(req); const id = req.params?.sessionId; if (!UUID.test(id ?? '')) throw error('NOT_FOUND', 'Session not found'); if (header(req, 'content-type') !== 'application/x-risu-local-model-image') throw error('INVALID_ARGUMENT', 'Invalid image content type'); if (!['image/jpeg', 'image/png', 'image/webp'].includes(header(req, 'x-risu-local-model-media-type'))) throw error('INVALID_ARGUMENT', 'Invalid image media type'); if (header(req, 'transfer-encoding') !== undefined) throw error('INVALID_ARGUMENT', 'Invalid image length'); const image = await body(req, header(req, 'content-length') ?? ''); const controller = new AbortController(); req.once?.('aborted', () => controller.abort()); res.once?.('close', () => controller.abort()); respond(res, await broker.run({ ...ids, profileId: profile(req), sessionId: id, image, options: options(header(req, 'x-risu-local-model-options')), signal: controller.signal })); } catch (e) { safe(res, e); } });
    app.delete('/api/plugin-model-inference/:profileId/sessions/:sessionId', async (req, res) => { if (!await auth(req, res, true)) return; try { const ids = owner(req); empty(req); const id = req.params?.sessionId; if (!UUID.test(id ?? '')) throw error('NOT_FOUND', 'Session not found'); await broker.release({ ...ids, profileId: profile(req), sessionId: id }); respond(res, { released: true }); } catch (e) { safe(res, e); } });
}
module.exports = { registerPluginModelInferenceRoutes };
